volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  minio_data:
    driver: local

networks:
  db:
    driver: bridge

services:
  postgres:
    container_name: video_postgres
    image: postgres:latest
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./configs/.env.dev
    networks:
      - db
  
  pgadmin:
    container_name: pgadmin1
    image: dpage/pgadmin4:7.2
    env_file:
      - ./configs/.env.dev
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - db
  
  minio:
    container_name: video_storage
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - ./configs/.env.dev
    command: server /data --console-address ":9001"

    