volumes:
  postgres_data:
  pgadmin_data:
  minio_data:
  rabbitmq-lib:
  rabbitmq-log:

networks:
  db:
    driver: bridge

services:
  postgres:
    container_name: video_postgres
    image: postgres:latest
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./configs/.env.dev
    networks:
      - db
  
  pgadmin:
    container_name: pgadmin1
    image: dpage/pgadmin4:7.2
    env_file:
      - ./configs/.env.dev
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - db
  
  minio:
    container_name: video_storage
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - ./configs/.env.dev
    command: server /data --console-address ":9001"
  
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./configs/.env.dev
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  nginx:
    image: nginx:alpine  # Лёгкий образ на Alpine Linux
    ports:
      - "80:80"  # Пробрасываем порт 80 хоста в контейнер
    volumes:
      - ./html:/usr/share/nginx/html  # Маппинг папки с HTML
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf  # Конфиг Nginx
    restart: unless-stopped  # Автоперезапуск при падении
