apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: video-processing-
spec:
  entrypoint: main
  volumes:
    - name: workspace
      emptyDir: {}

  templates:
    - name: main
      steps:
        - - name: download-and-process
            template: unified-processor

    - name: unified-processor
      container:
        # image: ubuntu:22.04  # Используем Ubuntu вместо Alpine
        # image: localhost:5000/ubuntu:1.0
        image: localhost:5000/ffmpeg-minio:alpine-1.0
        command: ["sh", "-c"]
        args:
          - |
            # Настройка MinIO клиента
            mc alias set minio http://minio.minio.svc.cluster.local:9000 minioadmin minioadmin

            # Скачивание файла
            mc cp minio/videos/input.mp4 /mnt/workspace/input.mp4

            # Обработка видео
            ffmpeg -i /mnt/workspace/input.mp4 -c:v libx264 /mnt/workspace/output.mp4

            # Загрузка результата
            mc cp /mnt/workspace/output.mp4 minio/videos/output.mp4
        volumeMounts:
          - name: workspace
            mountPath: /mnt/workspace
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "2Gi"