apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup-notifications
  namespace: minio
spec:
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc:latest
        command:
        - /bin/sh
        - -c
        - |
          until mc alias set minio http://minio:9000 minioadmin minioadmin; do
            echo "Ожидание MinIO...";
            sleep 5;
          done;

          # 2. Настраиваем webhook
          mc admin config set minio notify_webhook:webhook1 \
            endpoint="http://fastapi-service.default.svc.cluster.local:8000/webhook"

          sleep 15

          mc event add minio/videos arn:minio:sqs::1:webhook --event put || \
          mc admin bucket notify add minio/videos \
           http://fastapi-service.default.svc.cluster.local:8000/webhook --events put;

          echo "Список событий:";
          mc event list minio/videos;
          
          echo "Настройка завершена успешно";
      restartPolicy: Never
  backoffLimit: 3