apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-crd-installer
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-crd-installer-role
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-crd-installer-binding
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-crd-installer-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-crd-installer
  namespace: {{ .Release.Namespace }} 
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-install-traefik-crds
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-crd-installer
      restartPolicy: Never
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command: ["sh", "-c"]
        args:
          - |
            kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml