apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: upload-route
spec:
  parentRefs:
    - name: traefik-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /upload
      backendRefs:
        - name: upload-service
          port: 8080