apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-rolebinding
  namespace: argo-events
subjects:
- kind: ServiceAccount
  name: argo-events-sa
  namespace: argo-events
roleRef:
  kind: Role
  name: argo-events-role
  apiGroup: rbac.authorization.k8s.io