apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: video-processing-events
  namespace: argo-events
spec:
  http:
    video-processing:
      port: "12000"  # Порт, на котором будет слушать EventSource
      endpoint: "/video-processing"
      method: "POST"
      # Здесь указываем Service!
      service:
        ports:
          - port: 12000  # Порт Service
            targetPort: 12000  # Порт Pod
        type: ClusterIP  # Тип Service