apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio  # Указываем namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio  # Указываем namespace
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        args:
        - server
        - /data
        - --console-address
        - ":9001"  # Явно указываем порт консоли
        env:
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minioadmin"
        ports:
        - containerPort: 9000  # Порт для S3 API
          name: s3
        - containerPort: 9001  # Порт для веб-интерфейса
          name: console
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio  # Указываем namespace
spec:
  type: NodePort
  ports:
    - port: 9000  # Внешний порт для S3 API
      targetPort: 9000
      nodePort: 30090
      name: s3
    - port: 9001  # Внешний порт для консоли
      targetPort: 9001
      nodePort: 30091
      name: console
  selector:
    app: minio