apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: full-argo-access
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflowtaskresults", "workflowtasksets", "workflowtemplates"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-default-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-argo-access
subjects:
- kind: ServiceAccount
  name: fastapi-external-sa
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-full-access
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflowtaskresults", "workflowtasksets", "workflowtemplates"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-fastapi-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-full-access
subjects:
- kind: ServiceAccount
  name: fastapi-external-sa
  namespace: argo
  #---------
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-default-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-full-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo